[package]
name = "aas-benchmark"
version = "0.1.1"
authors = ["Alexander Korn <a@lxnd.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "2.33.3", features = ["yaml"]}
rand = "0.7"
